//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullBar.Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_TESTEEntities : DbContext
    {
        public DB_TESTEEntities()
            : base("name=DB_TESTEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TB_Aluno> TB_Aluno { get; set; }
        public DbSet<TB_Curso> TB_Curso { get; set; }
        public DbSet<TB_Periodo> TB_Periodo { get; set; }
    }
}
