//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullBar.Core
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class TB_Aluno
    {
        public int idAluno { get; set; }
        public string Nome { get; set; }
        public string RA { get; set; }
        public Nullable<int> idPeriodo { get; set; }
        public Nullable<int> idCurso { get; set; }
    
        public virtual TB_Periodo TB_Periodo { get; set; }

        public Boolean IsNew { get { return this.idAluno == 0; } }
    }

    public class UsuarioFiltros{
        public IList<TB_Curso> tbcurso {get;set;}

        public IList<TB_Periodo> tbperiodo {get;set;}

        public IList<TB_Aluno> tbaluno { get; set; }
    
    }
}
