//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullBar.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Curso
    {
        public int idCurso { get; set; }
        public string Curso { get; set; }
    
        public virtual TB_Curso TB_Curso1 { get; set; }
        public virtual TB_Curso TB_Curso2 { get; set; }
    }
}
