//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullBar.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Periodo
    {
        public TB_Periodo()
        {
            this.TB_Aluno = new HashSet<TB_Aluno>();
        }
    
        public int idPeriodo { get; set; }
        public string Periodo { get; set; }
    
        public virtual ICollection<TB_Aluno> TB_Aluno { get; set; }
    }
}
